//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public int id { get; set; }
        public string DecisionName { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<int> ComID { get; set; }
        public string ParentCompany { get; set; }
        public string ComName { get; set; }
        public string ComAddress { get; set; }
        public string Requester { get; set; }
        public string Director { get; set; }
        public string SystemName { get; set; }
        public string Description { get; set; }
        public string SoftApplication { get; set; }
        public string ListInvPattern { get; set; }
        public string Purpose { get; set; }
        public string Workflow { get; set; }
        public string Responsibility { get; set; }
        public string EffectiveDate { get; set; }
        public string EffectDate { get; set; }
        public string City { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string TechDepartment { get; set; }
        public string Destination { get; set; }
    }
}
