//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hddt_qldv_tester_Entities : DbContext
    {
        public hddt_qldv_tester_Entities()
            : base("name=hddt_qldv_tester_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<InvCategory> InvCategories { get; set; }
        public virtual DbSet<InvoiceTemplate> InvoiceTemplates { get; set; }
        public virtual DbSet<InvTemplate> InvTemplates { get; set; }
        public virtual DbSet<KeyStore> KeyStores { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<RegisterTemp> RegisterTemps { get; set; }
        public virtual DbSet<ServicePackage> ServicePackages { get; set; }
        public virtual DbSet<TaxAuthority> TaxAuthorities { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
