//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hddt_dhql_Entities : DbContext
    {
        public hddt_dhql_Entities()
            : base("name=hddt_dhql_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dhql_functional_authority> dhql_functional_authority { get; set; }
        public virtual DbSet<dhql_rank> dhql_rank { get; set; }
        public virtual DbSet<dhql_role> dhql_role { get; set; }
        public virtual DbSet<dhql_user> dhql_user { get; set; }
    }
}
