//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTemplate
    {
        public int Id { get; set; }
        public Nullable<int> InvCateID { get; set; }
        public string InvCateName { get; set; }
        public string TemplateName { get; set; }
        public string XmlFile { get; set; }
        public string XsltFile { get; set; }
        public string ServiceType { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceView { get; set; }
        public string IGenerator { get; set; }
        public string IViewer { get; set; }
        public string UploadService { get; set; }
        public string ParseService { get; set; }
        public string CssData { get; set; }
        public string CssLogo { get; set; }
        public string CssBackgr { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsPub { get; set; }
        public Nullable<bool> IsCertify { get; set; }
        public Nullable<int> TemCateID { get; set; }
    }
}
