//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyStore
    {
        public int Id { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<decimal> Type { get; set; }
        public string Path { get; set; }
        public string Password { get; set; }
        public Nullable<int> SlotIndex { get; set; }
        public string SerialCert { get; set; }
        public int KeyStoresOf { get; set; }
    }
}
