//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public int id { get; set; }
        public Nullable<int> ComID { get; set; }
        public string EmailFrom { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Type { get; set; }
        public string TemContent { get; set; }
        public string EmailFromLabel { get; set; }
    }
}
