//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish
    {
        public int id { get; set; }
        public Nullable<int> ComID { get; set; }
        public string Code { get; set; }
        public string ComName { get; set; }
        public string ComAddress { get; set; }
        public string ComPhone { get; set; }
        public string ComTaxCode { get; set; }
        public string RepresentPerson { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string TaxAuthorityCode { get; set; }
        public string TaxAuthorityName { get; set; }
        public string City { get; set; }
        public string Delimiter { get; set; }
    }
}
