//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterTemp
    {
        public int Id { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> InvCateID { get; set; }
        public Nullable<decimal> PatternOrder { get; set; }
        public string InvPattern { get; set; }
        public string Name { get; set; }
        public string NameInvoice { get; set; }
        public string CssData { get; set; }
        public string CssLogo { get; set; }
        public string CssBackgr { get; set; }
        public Nullable<bool> IsCertify { get; set; }
        public string ICertifyProvider { get; set; }
        public Nullable<int> TempID { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
