//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATInvoice
    {
        public int id { get; set; }
        public Nullable<decimal> No { get; set; }
        public Nullable<int> InvCateID { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public string Serial { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> ComID { get; set; }
        public string ComName { get; set; }
        public string ComPhone { get; set; }
        public string ComAddress { get; set; }
        public string ComTaxCode { get; set; }
        public string ComBankName { get; set; }
        public string ComBankNo { get; set; }
        public string ComFax { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string Buyer { get; set; }
        public string CusAddress { get; set; }
        public string CusPhone { get; set; }
        public string CusBankName { get; set; }
        public string CusBankNo { get; set; }
        public string CusTaxCode { get; set; }
        public string CusEmail { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<double> VATRate { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmountInWords { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> Converted { get; set; }
        public string KindOfService { get; set; }
        public Nullable<int> CusSignStatus { get; set; }
        public string CreateBy { get; set; }
        public string PublishBy { get; set; }
        public string Note { get; set; }
        public string Extra { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public string ProcessInvNote { get; set; }
        public string Fkey { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> VatAmount0 { get; set; }
        public Nullable<decimal> GrossValue0 { get; set; }
        public Nullable<decimal> VatAmount5 { get; set; }
        public Nullable<decimal> GrossValue5 { get; set; }
        public Nullable<decimal> VatAmount10 { get; set; }
        public Nullable<decimal> GrossValue10 { get; set; }
        public Nullable<bool> Certified { get; set; }
        public string CertifiedID { get; set; }
        public string CertifiedData { get; set; }
        public string ParentName { get; set; }
        public Nullable<decimal> VATOther { get; set; }
        public Nullable<decimal> ChangeFees { get; set; }
        public Nullable<decimal> ExtraFees { get; set; }
        public Nullable<decimal> OtherFees { get; set; }
        public string PortalLink { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string ShipTo { get; set; }
        public string SO { get; set; }
        public string TransNo { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> NoneVat { get; set; }
        public Nullable<bool> Vat0 { get; set; }
        public Nullable<bool> Vat5 { get; set; }
        public Nullable<bool> Vat10 { get; set; }
        public string Extra1 { get; set; }
        public string Option { get; set; }
        public Nullable<int> Active { get; set; }
        public string KeyImport { get; set; }
        public Nullable<int> SttImport { get; set; }
        public Nullable<int> DecimalCustomType { get; set; }
        public Nullable<System.DateTime> ConvertDate { get; set; }
        public Nullable<int> TotalRows { get; set; }
        public Nullable<int> TypeInv { get; set; }
        public Nullable<int> is_syns { get; set; }
        public Nullable<int> time_syns { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string DonViTien { get; set; }
    }
}
